### ISSUE TITLE
"Query Logging is Disabled" - Not sure why?

### ISSUE THREAD

**Issue by atrauzzi** [doctrine/DoctrineMongoDBBundle#107]
Situation:

I'm in the process of trying to get the sensio/framework-extra-bundle's DoctrineParamConverter working with MongoDB.

Problem:

Unfortunately, I can't really tell if the DB is being queried at all, because when I go to the Symfony Profiler and click the "Doctrine MongoDB" tab, I get the message "Query logging is disabled."

I'm fairly certain I have the MongoDB Bundle up and running in my project, as I don't think I'd be getting this tab otherwise.

The real confusion is that by all accounts, I think I should be getting logging by default while in development mode.  In Configuration.php, I'm seeing:

```
    ->booleanNode('logging')->defaultValue('%kernel.debug%')->end()
    ->arrayNode('profiler')
        ->addDefaultsIfNotSet()
        ->treatTrueLike(array('enabled' => true))
        ->treatFalseLike(array('enabled' => false))
        ->children()
            ->booleanNode('enabled')->defaultValue('%kernel.debug%')->end()
            ->booleanNode('pretty')->defaultValue('%kernel.debug%')->end()
        ->end()
```

Here's the chunk of YAML that I'm using to configure things:

```
    doctrine_mongodb:
      connections:
          default:
              server: mongodb://localhost:27017
              options:
                  connect: true
      default_database: nerve
      document_managers:
          default:
            auto_mapping: true
```

So, even if there was an issue with my ParamConverter - at the very least I should be able to see whether queries have been run or not by simply adding the MongoDB Bundle to my kernel and checking it in the profiler.

This does not appear to be the case.  Thanks for hearing me out!
