### ISSUE TITLE
Authentication against wrong database

### ISSUE THREAD

**Issue by advancingu** [doctrine/DoctrineMongoDBBundle#154]
I'm getting what appears to be incorrect behavior when asking this bundle to connect me to a MongoDB with authentication. Essentially, it appears that authentication is performed against the 'admin' database instead of the database specified in the `default_database` field according to [the documentation](http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html#full-default-configuration).

This is the configuration I am using:

```
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongo_host%
            options:
                username: %mongo_user%
                password: %mongo_password%
    default_database: %mongo_database%
```

This causes authentication to fail in `Doctrine\MongoDB\Connection at line 98`, with the following exception message:

```
Couldn't authenticate with database admin: username [myuser]
```

When I change the configuration to the following, everything works fine:

```
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%mongo_user%:%mongo_password%@%mongo_host%
    default_database: %mongo_database%
```

The other workaround is to leave the initial configuration but add the user to the 'admin' database, however it's not a good idea to have users running with admin rights.
