### ISSUE TITLE
Exception when disabling logging through config

### ISSUE THREAD

**Issue by scoolen** [doctrine/DoctrineMongoDBBundle#168]
`Connection::log()` always calls `$this->config->getLoggerCallable()`, but when logging is disabled `Configuration::setLoggerCallable()` is never called and no valid callback is returned.

Config:

``` yml
doctrine_mongodb:
    document_managers:
        default:
            logging: false
```

Result:

``` php
ErrorException: Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /[yada]/lib/symfony/2.1/vendor/doctrine/mongodb/lib/Doctrine/MongoDB/Connection.php line 144
```
