### ISSUE TITLE
Invalid modifier specified $unset

### ISSUE THREAD

**Issue by amine2z** [doctrine/DoctrineMongoDBBundle#175]
Hello,
I have this strange exception when i use mongodb ODM in command that save data.
I think that they come from configuration of bundle in prod env. Because i dont have any problem in my dev environnement.

[MongoCursorException]  
  localhost:27017: Invalid modifier specified $unset

This my config.yml for configuration of the bundle

``` yaml
doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: battal_database
    document_managers:
        default:
            auto_mapping: true
            mappings: ~
```

Thank you
