### ISSUE TITLE
Multiple connections/document managers configuration question and proposal

### ISSUE THREAD

**Issue by vmelnik-ukraine** [doctrine/DoctrineMongoDBBundle#213]
Hi, guys. I tried to setup multiple connections and document managers and saw interesting thing.

At `DoctrineMongoDBExtension::loadDocumentManager` we have next priority of database names for document manager (from higher to lower):
- option `database` in current document manager
- `default_database` option from `doctrine_mongodb`

code sample:

``` php
$defaultDatabase = isset($documentManager['database']) ? $documentManager['database'] : $defaultDB;
```

Also at `connections` section we can provide `options.db` for each connection. For me it's strange that when I write config like this:

```
connections:
    ...
    specific_connection:
        server: mongodb://localhost:27017
        options: { db: specific_db }
document_managers:
    ...
    specific_manager:
        connection: specific_connection
```

manager `specific_manager` works with database named `default`. I provided `specific_connection` with configured database address and name to it, why does global default parameters are higher in priority than custom provided connection options? I suppose there must be some reasons for that, can anyone explain them?
Is it a good idea to add one more check to database list priority?
