### ISSUE TITLE
Wrong parameter name for config of database name in DoctrineMongoDBExtension

### ISSUE THREAD

**Issue by fspillner** [doctrine/DoctrineMongoDBBundle#22]
You cannot define custom database name in your config.yml, for example: 

``` yaml
document_managers: 
  default: 
    database: yourDatabase
    mappings: 
      YourBundle: { type: annotation, dir: Document }
```
