### ISSUE TITLE
  Unrecognized options "persist" under "doctrine_mongodb.connections.default.options"

### ISSUE THREAD

**Issue by FlxPeters** [doctrine/DoctrineMongoDBBundle#229]
``` yaml
doctrine_mongodb:
   connections:
        # Prototype
        id:
            server:               ~
            options:
                connect:              ~
                persist:              ~
                timeout:              ~
                replicaSet:           ~
                username:             ~
                password:             ~
                db:                   ~
```
Following the [Documentation] (http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html#full-default-configuration) there should be the Option "persist" for a Connection to set a Connection as persistent: [Persistent Connections](http://de3.php.net/manual/en/mongo.connecting.persistent.php)

When i use this i get this:

````  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized options "persist" under "doctrine_mongodb.connections.default.options"
````
Where is this Option and how can i persist Connections? 

I have some Problems with a MongoCursorTimeoutException when connection multiple Tasks to the Database. Maybe this could fix the Problem.

My config:

````doctrine_mongodb:
    auto_generate_hydrator_classes: %kernel.debug%
    auto_generate_proxy_classes: %kernel.debug%
    connections:
        default:
            server: %mongodb_server%
            options:
                #connect:              ~
                persist:              'someKey'
```
