### ISSUE TITLE
Documentation bug on multiple databases

### ISSUE THREAD

**Issue by redthor** [doctrine/DoctrineMongoDBBundle#241]
Thanks for the bundle.

Contrary to the documentation  on configuration:
http://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html#full-default-configuration

I find that this does not work:

``` yml
doctrine_mongodb:
    connections:
        domain:
            server: %db_domain_server%
            options:
                db: %db_domain_db%
        query:
            server: %db_query_server%
            options:
                db: %db_query_db%
    document_managers:
        MyBundle:
            connection: domain
            auto_mapping: true
        MyDomainBundle:
            connection: domain
            auto_mapping: true
        MyQueryBundle:
            connection: query
            auto_mapping: true
```

But if I remove `db: %db_domain_db%` from the connection config and add `database: %db_domain_db%` to the document manager config, like this:

``` yml
doctrine_mongodb:
    connections:
        domain:
            server: %db_domain_server%
        query:
            server: %db_query_server%
    document_managers:
        MyBundle:
            database: %db_domain_db%
            connection: domain
            auto_mapping: true
        MyDomainBundle:
            database: %db_domain_db%
            connection: domain
            auto_mapping: true
        MyQueryBundle:
            database: %db_query_db%
            connection: query
            auto_mapping: true
```

it will work.

That is, set the default database on the document manager, not the connection.

I think this is the related code:
https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/DependencyInjection/DoctrineMongoDBExtension.php#L143

And, actually, this ticket may be a duplicate, this seems similar:
https://github.com/doctrine/DoctrineMongoDBBundle/issues/213

thanks
