### ISSUE TITLE
Passing null values as username/password option causes authentication to occur and fail

### ISSUE THREAD

**Issue by vmattila** [doctrine/DoctrineMongoDBBundle#243]
Consider following configuration in Symfony's `config.yml`:

``` yaml
doctrine_mongodb:
  connections:
    default:
      server: %mongodb.default.server%
      options:
          username: %mongodb.default.username%
          password: %mongodb.default.password%
```

Everything works well when %mongodb.default.username% and %mongodb.default.password% have some values defined. If they are set as null in the `parameters.yml` with `mongodb.default.username = ~`, the authentication occurs against the MongoDB and it most propably fail.

The problem here is that bundle's configuration `options` array is passed as is to the MongoDB driver. MongoDB driver seem to do authentication whenever there is `username` item, but at this point `null` converts to empty string.

There is relatively easy workaround: move `options` configuration node fully to a parameter (like `%mongodb.default.options%`) and leave username and password completely away from there when authentication is not used. Unfortunately this requires that the whole `options` array is configured in `parameters.yml`, even the parameters that are not actually configurable per installation. Sometimes it's not desirable or not even possible to keep BC.

What I'd like to see is that if null values are set in `doctrine_mongodb.connect.<default>.options.(username|password)` nodes, the would be removed before passing them to the MongoDB Driver.
