### ISSUE TITLE
Two ODM Document Managers can't work together injected as services

### ISSUE THREAD

**Issue by rickmuca** [doctrine/DoctrineMongoDBBundle#244]
My problem is that I have configured two document managers like this:

``` yaml
doctrine_mongodb:
    document_managers:
        video:
            connection: video
            auto_mapping: true
        stats:
            connection: stats
            auto_mapping: true
    connections:
        video:
            server: mongodb://mongo0:27017,mongo1:27017
            options:
                connect: true
                replicaSet: true
                slaveOkay: true
        stats:
            server: mongodb://mongo2:27017,mongo3:27017
            options:
                connect: true
                replicaSet: true
                slaveOkay: true
    default_document_manager: video
    default_connection: video
    default_database: my_database"
```

I have the same name for both databases and when I load my page it seems everything's ok (loading my page I only use the 'video' document manager). However, if I use the 'stats' document manager after, symfony seems going crazy.

I have the document managers injected as services like this:

``` ruby
stats_service:
    class: %stats_service.class%
    arguments: 
      - @doctrine_mongodb.odm.stats_document_manager
video_service:
    class: %video_service.class%
    arguments: 
      - @doctrine_mongodb.odm.video_document_manager
```

I don't know why, but it seems like every time I do a query, symfony use one of the connections randomly, not the connection of the document manager injected.
