### ISSUE TITLE
does not let define connections without document manager?

### ISSUE THREAD

**Issue by cordoval** [doctrine/DoctrineMongoDBBundle#257]
it seems the bundle does not let us specify connections without managers

if i remove the bottom lines below for the custom manager the bundle breaks without doing the connections, is this normal behavior?

```yaml
doctrine_mongodb:
    connections:
        default:
            server: %mongodb_connections_server%
            options:
                username: %mongodb_connections_username%
                password: %mongodb_connections_password%
                replicaSet: %mongodb_connections_replicaset%
                db: %mongodb_connections_db%
        custom:
            server: %mongodb_connections_custom_server%
            options:
                db: custom
                readPreference: secondaryPreferred
    default_database: %mongodb_connections_db%
    document_managers:
        default:
            auto_mapping: true
        custom:
            connection: custom
```
