### ISSUE TITLE
Allow using variables in schema files

### ISSUE THREAD

**Issue by TomiS** [doctrine/DoctrineMongoDBBundle#284]
At the moment all data in schema files must be hardcoded (afaik). I would like to be able to do following:

```
My\FunkyBundle\Document\FunkRecord:
    type: document
    collection: %my_funky.collection_name%
    fields:
        id:
            id: true
    referenceMany:
        songs: 
            targetDocument: %my_funky.classes.song%
```
It would be consistent with how other Symfony configs work.
