### ISSUE TITLE
TokenStorage is lost when injected into eventlistener

### ISSUE THREAD

**Issue by meigallodixital** [doctrine/DoctrineMongoDBBundle#287]
### Listener code

```
<?php
namespace Project\ProductoBundle\EventListener;

use Doctrine\ODM\MongoDB\Event\PreUpdateEventArgs;
use Project\ProductoBundle\Document\Producto;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;

class PreUpdateListener
{
    private $gestor;

    public function __construct(TokenStorage $token)
    {
        $this->gestor = $token->getToken()->getUser();
    }
...
```
### Service configuration

```
 producto.preupdate.listener:
        class: Project\ProductoBundle\EventListener\PreUpdateListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
```

Token is always null. With ORM works ok. Event listener executes ok if we comment token asignation.

**Note:** We use user session into mongodb database.
