### ISSUE TITLE
Database turned to 'default' when authentication is correct 

### ISSUE THREAD

**Issue by Sshuichi** [doctrine/DoctrineMongoDBBundle#295]
Hi ! 
This is my config : 

```
doctrine_mongodb:
    connections:
        default:
            server: 'mongodb://localhost:27017,localhost:27018,localhost:27019'
            options:
                username: sshuichi
                password: complexpassword
                db: mydb 
```

When the password is not correct , I have this error : 

> Failed to connect to: localhost:27017: Authentication failed on
> database 'mydb' with username 'sshuichi': auth failed; Failed to
> connect to: localhost:27018: Authentication failed on database 'mydb'
> with username 'sshuichi': auth failed; Failed to connect to:
> localhost:27019: Authentication failed on database 'mydb' with
> username 'sshuichi': auth failed

Please notice it's talking about `mydb`

When the password is correct, I have 

> not authorized on default to execute command

Why on earth is it talking about default this time ?
