### ISSUE TITLE
[Question] Multiple database configuration

### ISSUE THREAD

**Issue by aRn0D** [doctrine/DoctrineMongoDBBundle#318]
I configured two connections in my symfony projet, one of our collection is in an extra database. See my config : 

```yaml
# config.yml
doctrine_mongodb:
    connections:
        default:
            server: %default_database_server%
            options:
                username: %default_database_user%
                password: %default_database_password%
                db: %default_database_name%
                replicaSet: %default_database_replicaset%
                connect: true
        video:
            server: %video_database_server%
            options:
                username: %video_database_user%
                password: %video_database_password%
                db: %video_database_name%
                replicaSet: %video_database_replicaset%
                connect: true
    document_managers:
        default:
            connection: default
            mappings:
                MyBundle: ~
        video:
            connection: video
            mappings:
                MyBundle: ~
    default_database: %default_database_name%
    default_document_manager: default
    default_connection: default
```

I created a repository which uses the `video` document manager, it is defined as a service : 

```yaml
# service.yml
services:
    gsoi_content.video.repository:
        class: %gsoi_content.repository.video.class%
        factory_service: doctrine_mongodb.odm.video_document_manager
        factory_method: getRepository
        arguments:
            - %gsoi_content.model.video.class%
```

The problem is that Doctrine tries to look for data in the wrong database. It uses the default datable all the time. I found that in `DoctrineMongoDBExtension::loadDocumentManager()` line 147
```php
 $defaultDatabase = isset($documentManager['database']) ? $documentManager['database'] : $defaultDB;
```

`$documentManager['database']` is never defined. So, did I do something wrong? Perhaps, we should merge the database configured for the connection to `$documentManager`

Thanks.
