### ISSUE TITLE
Override YamlDriver::DEFAULT_FILE_EXTENSION through configuration file

### ISSUE THREAD

**Issue by nbochenko** [doctrine/DoctrineMongoDBBundle#320]
Hi all,
Is that possible to override the '.mongodb.yml' via configuration file?

```
services:
  doctrine_mongodb.odm.metadata.yml:
    class: %doctrine_mongodb.odm.metadata.yml.class%
    arguments:
      - %doctrine_mongodb.odm.yml_mapping_dirs%
      - "something.yml"
```

Does not work.
