### ISSUE TITLE
The service [connection] has a dependency on a non-existent service [configuration].

### ISSUE THREAD

**Issue by MatTheCat** [doctrine/DoctrineMongoDBBundle#432]
Here is my configuration:

```yaml
doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options: {}
    document_managers:
        auth_token:
            connection: default
            database: symfony
            mappings:
                SendinBlue:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: SendinBlue\Document\AuthToken
        user:
            connection: default
            database: central_db
            mappings:
                SendinBlue:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: SendinBlue\Document\User
```

I got two databases on the same connection so I thought this would work but I get

> The service "doctrine_mongodb.odm.default_connection" has a dependency on a non-existent service "doctrine_mongodb.odm.default_configuration".

Did I do wrong or is this a problem in `DoctrineMongoDBExtension`?
