### ISSUE TITLE
"SCRAM-SHA-1" authentication mechanism requires libmongoc built with --enable-ssl

### ISSUE THREAD

**Issue by velkony** [doctrine/DoctrineMongoDBBundle#450]
Hi @omnidan,
I would like to use DoctrineMongoDBBundle in my project with MongoDB 3.6 and PHP 7.2
I have the following problem: 
"SCRAM-SHA-1" authentication mechanism requires libmongoc built with --enable-ssl
when I am creating a user in the database.

When I use locally database, there is no problem.

I have set the following settings:
```
doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: mongodb://79.98.104.XXX:27017
            options:
                password: YYYY
                username: admin
                authSource: admin
                ssl: false
                authMechanism: SCRAM-SHA-1

    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: App\Document\
                    alias: App
```

I would like to know what settings to set.

Thank you for your time
