### ISSUE TITLE
Class 'PHPUnit\Framework\TestCase' not found on fixtures:load

### ISSUE THREAD

**Issue by Ghriim** [doctrine/DoctrineMongoDBBundle#468]
When I run:
`php bin/console doctrine:mongodb:fixtures:load --quiet`

I have the following error:
```
PHP Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /home/quentin/Developpements/perso/shf-api/vendor/symfony/framework-bundle/Test/KernelTestCase.php on line 24
PHP Fatal error: Class 'PHPUnit\Framework\TestCase' not found in /home/quentin/Developpements/perso/shf-api/vendor/symfony/web-profiler-bundle/Tests/TestCase.php on line 16
```

My composer.json is:
```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "alcaeus/mongo-php-adapter": "^1.1",
        "doctrine/mongodb-odm-bundle": "^3.4",
        "friendsofsymfony/rest-bundle": "^2.3",
        "knplabs/knp-paginator-bundle": "^2.8",
        "lexik/jwt-authentication-bundle": "^2.4",
        "nelmio/api-doc-bundle": "^3.2",
        "symfony/asset": "^4.1",
        "symfony/browser-kit": "^4.1",
        "symfony/console": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/form": "^4.1",
        "symfony/framework-bundle": "^4.1",
        "symfony/lts": "^4@dev",
        "symfony/monolog-bundle": "^3.3",
        "symfony/property-access": "^4.1",
        "symfony/security-bundle": "^4.1",
        "symfony/serializer": "^4.1",
        "symfony/translation": "^4.1",
        "symfony/twig-bundle": "^4.1",
        "symfony/validator": "^4.1",
        "symfony/yaml": "^4.1"
    },
    "require-dev": {
        "symfony/dotenv": "^4.1",
        "symfony/phpunit-bridge": "^4.1",
        "symfony/profiler-pack": "^1.0",
        "symfony/web-server-bundle": "^4.1"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "platform": {
            "ext-mongo": "1.6.7"
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": "true"
        }
    }
}

```

Config doctrine_mongodb.yaml:
```
doctrine_mongodb:
    auto_generate_proxy_classes: '%kernel.debug%'
    auto_generate_hydrator_classes: '%kernel.debug%'
    connections:
        default:
            server: '%env(MONGODB_URL)%'
            options:
                username: '%env(MONGODB_USERNAME)%'
                password: '%env(MONGODB_PASSWORD)%'
    default_database: '%env(MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: yml
                    dir: '%kernel.project_dir%/config/doctrine'
                    prefix: 'App\Document'
                    alias: App
    fixture_loader: Symfony\Bridge\Doctrine\DataFixtures\ContainerAwareLoader
```
