### ISSUE TITLE
[Regression] Multiple document_managers fail with 3.5.0

### ISSUE THREAD

**Issue by hjanuschka** [doctrine/DoctrineMongoDBBundle#477]
hello,

first of all thx for this great project we ❤️  it.

using the following yaml:

# 3.4.4

```
parameters:
    env(KRN_HOST_MONGODB_PRIMARY): 'mongo_primary.krn.krone.at'
    env(KRN_HOST_MONGODB_SECONDARY): 'mongo_secondary.krn.krone.at'
    env(MONGODB_DEFAULT_SERVER): "mongodb://%env(KRN_HOST_MONGODB_PRIMARY)%,%env(KRN_HOST_MONGODB_SECONDARY)%:27017"
    env(MONGODB_DEFAULT_CONN): 'krn_default'

doctrine_mongodb:
    default_database: krn_api
    default_connection: '%env(MONGODB_DEFAULT_CONN)%'
    default_document_manager: krn_default

    connections:
        krn_default:
            server: "%env(MONGODB_DEFAULT_SERVER)%"
            options:
                replicaSet: "rs0"

    document_managers:
        krn_default:
            connection: krn_default
            database: krn_api
            #auto_mapping: true
            mappings:
                KRNApiBundle: ~
        krn_lunar_calendar:
            connection: krn_default
            database: krn_lunar_calendar
            mappings:
                KRNApiBundle: { type: annotation, prefix: KRNApiBundle\Document\LunarCalendar }
        krn_reader_letter:
            connection: krn_default
            database: krn_reader_letter
            mappings:
                KRNApiBundle: { type: annotation, prefix: KRNApiBundle\Document\ReaderLetter }
        krn_daily_horoscope:
            connection: krn_default
            database: krn_daily_horoscope
            mappings:
                KRNApiBundle: { type: annotation, prefix: KRNApiBundle\Document\DailyHoroscope }
```

running:
```
bin/console doctrine:mongodb:mapping:info
```

outputs:
```
Found 4 documents mapped in document manager krn_default:

[OK]   KRNApiBundle\Document\DailyHoroscope\ZodiacDay
[OK]   KRNApiBundle\Document\LunarCalendar\Day
[OK]   KRNApiBundle\Document\LunarCalendar\Zodiac
[OK]   KRNApiBundle\Document\ReaderLetter\Letter

```

# 3.5.0
upgrading to `3.5.0`

results in:

```
Found 1 documents mapped in document manager krn_default:

[OK]   KRNApiBundle\Document\DailyHoroscope\ZodiacDay

```

which breaks our application, i tried to dig threw the changelog, but doesnt seem to be any notice of a BC change.

any advices?

thx in advance

**Comment by hjanuschka** [comment]
ok moving 
```
        krn_default:
            connection: krn_default
            database: krn_api
            #auto_mapping: true
            mappings:
                KRNApiBundle: ~
 
```

bottm as the last manager, partially fixes it, output is OK

but still having problems inside the application - finding repositorys

**Comment by hjanuschka** [comment]
```
Exception trace:
 Doctrine\Common\Persistence\Mapping\MappingException::nonExistingClass() at /opt/API/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:24
 Doctrine\Common\Persistence\Mapping\RuntimeReflectionService->getParentClasses() at /opt/API/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:251
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getParentClasses() at /opt/API/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:284
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at /opt/API/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:183
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at /opt/API/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:287
 Doctrine\ODM\MongoDB\DocumentManager->getClassMetadata() at /opt/API/vendor/doctrine/mongodb-odm-bundle/Repository/ContainerRepositoryFactory.php:37
 Doctrine\Bundle\MongoDBBundle\Repository\ContainerRepositoryFactory->getRepository() at /opt/API/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/DocumentManager.php:524
 Doctrine\ODM\MongoDB\DocumentManager->getRepository() at /opt/API/src/KRNApiBundle/Services/MongoDocumentApi.php:15
 KRNApiBundle\Services\MongoDocumentApi->getMongoRepository() at /opt/API/src/KRNApiBundle/Services/MongoDocumentApi.php:36
 KRNApiBundle\Services\MongoDocumentApi->findMulti() at /opt/API/src/KRNApiBundle/Services/MongoDocumentApi.php:24
 KRNApiBundle\Services\MongoDocumentApi->find() at n/a:n/a
 call_user_func_array() at /opt/API/src/KRNApiBundle/Services/AbstractService.php:157
 KRNApiBundle\Services\AbstractService->getUncachedData() at /opt/API/src/KRNApiBundle/Services/MongoDocumentData.php:62
 KRNApiBundle\Services\MongoDocumentData->deleteDocuments() at /opt/API/src/KRNApiBundle/Services/Extern/ReaderLetter/LetterItem.php:115
 KRNApiBundle\Services\Extern\ReaderLetter\LetterItem->deleteItemsByDate() at /opt/API/src/KRNApiBundle/Services/manager/ReaderLetterManager.php:55
 KRNApiBundle\Services\manager\ReaderLetterManager->deleteReaderLetterItemsByDate() at /opt/API/src/KRNApiBundle/Services/Extern/ReaderLetter/ReaderLetterImporter.php:120
 KRNApiBundle\Services\Extern\ReaderLetter\ReaderLetterImporter->import() at /opt/API/src/KRNApiBundle/Services/Extern/ReaderLetter/ReaderLetterImporter.php:37
 KRNApiBundle\Services\Extern\ReaderLetter\ReaderLetterImporter->importByCommand() at /opt/API/src/KRNApiBundle/Command/ReaderLetter/ImportDayCommand.php:86
 KRNApiBundle\Command\ReaderLetter\ImportDayCommand->execute() at /opt/API/vendor/symfony/console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /opt/API/vendor/symfony/console/Application.php:904
 Symfony\Component\Console\Application->doRunCommand() at /opt/API/vendor/symfony/framework-bundle/Console/Application.php:89
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /opt/API/vendor/symfony/console/Application.php:262
 Symfony\Component\Console\Application->doRun() at /opt/API/vendor/symfony/framework-bundle/Console/Application.php:75
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /opt/API/vendor/symfony/console/Application.php:145
 Symfony\Component\Console\Application->run() at /opt/API/bin/console:39

krn:reader-letter:import-day [-s|--source-date SOURCE-DATE] [-z|--target-date [TARGET-DATE]] [-o|--allow-overwrite [ALLOW-OVERWRITE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by hjanuschka** [comment]
calling `->getRepository()`  with `KRNApiBundle::Letter`

**Comment by hjanuschka** [comment]
nevermind using `KRNApiBundle:ReaderLetter\\Letter` fixed it

**Comment by alcaeus** [comment]
The first “issue” is a side effect of #471. Previously, the configuration was stored per connection. To fix an issue when using multiple connections this was changed to being stored per document manager. That’s why you suddenly only see one document mapped, which would have been the correct configuration to begin with.

As for the second issue, that’s on #473 - I just don’t know what exactly is provoking it. I suggest using class names instead of that weird bundle syntax. Thanks to the ::class constant you’ll have a proper identifier instead of a magic string.

**Comment by hjanuschka** [comment]
@alcaeus thx for reply, the above fixes did'nt fix it 100% - i also had to remove my various doc-managers


and only kept:

```
    document_managers:
        krn_default:
            connection: krn_default
            database: krn_api
            #auto_mapping: true
            mappings:
                KRNApiBundle: ~

```

otherwise it ended up anyway in the default database.
so i removed them, and set the `db=`  in the `@Document`  annotation.
