### ISSUE TITLE
[Feature] allow to specify database name in the URL

### ISSUE THREAD

**Issue by dkarlovi** [doctrine/DoctrineMongoDBBundle#497]
Currently, the [database name is expected to be injected separately from the connection URL](https://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html#configuration):

```yaml
doctrine_mongodb:
    connections:
        default:
            server: "%mongodb_server%"
    default_database: test_database
```

This doesn't match [Doctrine's DBAL configuration](https://symfony.com/doc/current/bundles/DoctrineBundle/configuration.html#doctrine-dbal-configuration):

```yaml
doctrine:
    dbal:
        url: mysql://user:secret@localhost:1234/otherdatabase
```

which allows to specify a database directly in the URL.

I propose to allow setting the database name directly in the URL, if possible.

**Comment by malarzm** [comment]
If I'm not wrong, this is already possible: https://docs.mongodb.com/manual/reference/connection-string/

**Comment by dkarlovi** [comment]
@malarzm so I can just append the database, it's passed to the driver directly? Why is the bundle then using the `default_database` option as a default is the DSN seems like a preferred method of configuration?

**Comment by malarzm** [comment]
Looking at code, [this](https://github.com/doctrine/DoctrineMongoDBBundle/blob/454a0f7f0f22c236d2dbf588a3ecc2ff77cf7877/DependencyInjection/DoctrineMongoDBExtension.php#L159) is the only place where `default_database` is used, so it's passed to DocumentManager's configuration if it wasn't specified. The underlying connection will use database specified in DSN though.

**Comment by dkarlovi** [comment]
I'll test it and close here if it works. Maybe consider changing the default Symfony recipe and docs to reflect this?

**Comment by malarzm** [comment]
> Maybe consider changing the default Symfony recipe and docs to reflect this?

PR will be appreciated!

**Comment by jmikola** [comment]
> The underlying connection will use database specified in DSN though.

Note that the driver only uses the database name in the connection string as a fallback for the authentication database in the absence of an `authSource` URI option. If you are (a) using `authSource` or (b) not using authentication, then the database name is entirely ignored.

This is not to be confused with the `default_database` option in in Doctrine's configuration, which is likely used as the default database for storing model collections.

**Comment by dkarlovi** [comment]
@jmikola does that mean the database specified in the DSN doesn't get used except in special circumstances? That means it's not really currently supported.

**Comment by jmikola** [comment]
According to MongoDB's own documentation on [connection strings](https://docs.mongodb.com/manual/reference/connection-string/) the database name in the URI is only intended to be used for authentication. It it mostly a legacy artifact that is still supported for BC since the `authSource` option has superseded it.

Some libraries have chosen to use it for other purposes. For instance, I believe the [Mongoose](https://mongoosejs.com/) ODM for Node uses it for its default database for models. AFAIK, Doctrine has never supported that, nor has it ever had logic to extract the database component from a URI string.

This seems like a feature request for a future ODM version, if anything. For the time being, I think ODM would do well to clarify the current behavior in its documentation.

**Comment by alcaeus** [comment]
I believe it's best to keep the connection string format consistent with that MongoDB defines. Closing here.

**Comment by dkarlovi** [comment]
@alcaeus IMO that's a mistake since it makes a known use case harder for no real reason.

Note I'm not proposing the consistency with MongoDB gets somehow reduced. The database can literally be a new param in the query string, something like

```
doctrine_mongodb:
    connections:
        default:
            server: mongodb://db1.example.net:27017,db2.example.net:2500/?replicaSet=test&connectTimeoutMS=300000&odm_default_database=my_database
```

or similar.
