### ISSUE TITLE
Resolve target document seems to not working

### ISSUE THREAD

**Issue by emulienfou** [doctrine/DoctrineMongoDBBundle#548]
Hi there, new to MongoDB I'm trying to resolve a target document from a specific interface.

I currently using and testing both Doctrine ORM and MongoDB bundles to resolve a target entity/document from the `Symfony\Component\Security\Core\User\UserInterface`.
However, I seems to have an issue with this bundle.

Here is my configuration for both DoctrineBundle and DoctrineMongoDBBundle:
```yaml
doctrine:
    # ...
    orm:
        resolve_target_entities:
            Symfony\Component\Security\Core\User\UserInterface: App\Entity\User
```

```yaml
doctrine_mongodb:
    # ...
    resolve_target_documents:
        Symfony\Component\Security\Core\User\UserInterface: App\Document\User
```

And here is the code to resolve the class from the interface I test:
```php
$this->registry->getManager()
    ->getMetadataFactory()
    ->getMetadataFor(\Symfony\Component\Security\Core\User\UserInterface::class)
    ->getName();
```

--- 

With DoctrineMongoDBBUndle **only** I've got a `MappingException` with the next error message:

`Class 'Symfony\Component\Security\Core\User\UserInterface' does not exist`

Thanks for the help
