### ISSUE TITLE
Symfony 4 - Connect mongo documentDB using ssl params  

### ISSUE THREAD

**Issue by elangovanshanthi** [doctrine/DoctrineMongoDBBundle#593]
## Symfony - Connect mongo documentDB using ssl params  

I am trying to connect amazon mongo documentDB using `ssl params` like 
`--sslCAFile, --username, --password and --host` in symfony.

Can you provide example for connecting mongo documentDB in symfony4?

version : "doctrine/mongodb-odm-bundle": "^3.5"
Symfony4

**Comment by alcaeus** [comment]
The options you are mentioning are for the MongoDB shell and can be replicated using connection string options, which are listed in the [MongoDB documentation](https://docs.mongodb.com/manual/reference/connection-string/#connection-string-options).

For the authentication options (`username`, `password`, `authSource`, and `authMechanism`) we supply configuration options under the `options` for a connection:
```yml
doctrine_mongodb:
  connections:
    default:
      [...]
      options:
        username: "someUser"
        password: "superSecret"
```

Please note that the MongoDB ODM is built on top of the MongoDB PHP driver, which doesn't support "mongodb-like" databases like CosmosDB or Amazon DocumentDB, so you're mileage with these options may vary. That said, if my memory serves me correct you should be able to see a connection string that you can use to connect to the database in question.
