### ISSUE TITLE
"doctrine_mongodb" has no class

### ISSUE THREAD

**Issue by kumargowdaa** [doctrine/DoctrineMongoDBBundle#686]
The definition for "doctrine_mongodb" has no class. If you intended to inject this service dynamically at runtime , please mark it as synthetic=true.

**Comment by kumargowdaa** [comment]
@alcaeus  please help on this. Thanks

**Comment by franmomu** [comment]
Hi @kumargowdaa, I'm not sure what you are trying to do there, can you show the full example or give some context?

In that code there is no `doctrine_mongodb` usage, only defining `Doctrine\Bundle\MongoDBBundle` as a service which is kind of strange because bundles are not supposed to be defined as a services, they are instantiated by Symfony.

**Comment by kumargowdaa** [comment]
@franmomu thanks for the reply.

This is the issue I am facing.

Using Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler with the legacy mongo extension is deprecated as of 3.4 and will be removed in 4.0. Use it with the mongodb/mongodb package and ext-mongodb instead.

Composer.json I haved added this mongodb bundles

Symfony version I have used. 3.4.38
"alcaeus/mongo-php-adapter": "^1.2",
 "doctrine/mongodb-odm": "1.3.7",
 "doctrine/mongodb-odm-bundle": "3.4.4",

And in config.yml  I am using like this
 services:
  doctrine_mongodb:
    connections:
      default:
        server: "mongodb://%mongodb_connection_string%"
        options: {}
    default_database: %mongo_database%
    document_managers:
      default:
        auto_mapping: true
  session.handler.mongo:
    class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
    arguments: ["@mongo_client", "%mongo.session.options%"]

**Comment by franmomu** [comment]
> And in config.yml I am using like this
> services:
> doctrine_mongodb:
> connections:
> default:
> server: "mongodb://%mongodb_connection_string%"
> options: {}
> default_database: %mongo_database%
> document_managers:
> default:
> auto_mapping: true
> session.handler.mongo:
> class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
> arguments: ["@mongo_client", "%mongo.session.options%"]

Can you please format this `config.yml` file? Apparently looks like `doctrine_mongodb` is defined in the `services` key, if it looks like something like this:

```yaml
services:
  doctrine_mongodb:
     connections:
     #...
```

It's wrong, your configuration should look like: https://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/config.html#sample-configuration

To me, seems like you are mixing things here, what are you trying to do exactly? Looks like you want to store sessions using mongodb and for that you did this:

> Composer.json I haved added this mongodb bundles
> 
> Symfony version I have used. 3.4.38
> "alcaeus/mongo-php-adapter": "^1.2",
> "doctrine/mongodb-odm": "1.3.7",
> "doctrine/mongodb-odm-bundle": "3.4.4",

do you use the old `ext-mongo` driver? if not, you should install [`mongodb/mongodb`](https://github.com/mongodb/mongo-php-library) and install `ext-mongodb` driver.

Once you do that, following this: https://symfony.com/doc/3.4/doctrine/mongodb_session_storage.html you only need to change the mongo client class to use `\MongoDB\Client` instead of `MongoClient` and there is no need of `doctrine/mongodb-odm` nor `doctrine/mongodb-odm-bundle`.

**Comment by kumargowdaa** [comment]
@franmomu  thank you,

Yes I am using this to store sessions using mongodb.

Config.yml data I have posted throuh mobile so it's not formatted.

Please let me know which file I need to make this MongoDB\Client

Can u share me how I can install ext-mongodb.
Plase share me the Composer command for install ext-mongodb

Thanks in advance

**Comment by franmomu** [comment]
[`ext-mongodb` driver is a PHP extension](https://www.php.net/manual/en/set.mongodb.php), so it cannot be installed with composer, you can follow the instructions from:

https://github.com/mongodb/mongo-php-library#installation or https://www.php.net/manual/en/mongodb.installation.php

**Comment by kumargowdaa** [comment]
@franmomu ok thank you

Please let me know which file I need to make this MongoDB\Client

**Comment by franmomu** [comment]
Let's say you already have `ext-mongodb` extension installed and  also`mongodb/mongodb` in your composer, then you have to follow this documentation: https://symfony.com/doc/3.4/doctrine/mongodb_session_storage.html but where it says `MongoClient`, you would use `\MongoDB\Client`.

```yaml
# app/config/config.yml
framework:
    session:
        # ...
        handler_id:  session.handler.mongo
        cookie_lifetime: 2592000 # optional, it is set to 30 days here
        gc_maxlifetime: 2592000 # optional, it is set to 30 days here

services:
    # ...
    mongo_client:
        class: \MongoDB\Client
        # if not using a username and password
        arguments: ['mongodb://%mongodb_host%:27017']
    session.handler.mongo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\MongoDbSessionHandler
        arguments: ['@mongo_client', '%mongo.session.options%']
```
