### ISSUE TITLE
Unrecognized option "tlsCAFile"

### ISSUE THREAD

**Issue by hasc** [doctrine/DoctrineMongoDBBundle#698]
I am trying to connect to an AWS DocumentDB with TLS enabled. I see no way passing the ssl/tls caFile option.

I assume I should be able to configure this somehow like this:

```yaml
options:
    username: '%env(resolve:MONGODB_USERNAME)%'
    password: '%env(resolve:MONGODB_PASSWORD)%'
    ssl: '%env(bool:MONGODB_SSL)%'
    tlsCAFile: '/path/to/cafile.pem'
```

Are there any plans to add this options or reasons to not do so?
