### ISSUE TITLE
Support when@test

### ISSUE THREAD

**Issue by pcmanprogrammeur** [doctrine/DoctrineMongoDBBundle#732]
Hello,

When we make tests, the "when@test" instruction is very usefull, in doctrine.yaml, to specify a different database when running tests : 

```
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
```

It could be a good thing to make the same thing in this package like this in doctrine_mongodb.yaml :

```
when@test:
    doctrine_mongodb:
        document_managers:
            my_document_manager:
                database: '%env(resolve:URI_MONGO_DB)%_test'
```

What do you think about this feature ?

Thanks.
