### ISSUE TITLE
Move and extend Symfony 6.2 #[MapEntity] to support ODM as well

### ISSUE THREAD

**Issue by icvij** [doctrine/DoctrineMongoDBBundle#753]
I have created an issue on Symfony git repo and I've been told to open issue here.

As @fabpot and @shkabo suggested [here](https://github.com/symfony/symfony/issues/48835) **#[MapEntity]** can be moved from Symfony to here and add **#[MapDocument]** to support both ORM/ODM.

For more details take a look here: [issue](https://github.com/symfony/symfony/issues/48835)

**Comment by HypeMC** [comment]
Actually, despite the name, the `EntityValueResolver` & `#[MapEntity]` attribute work with MongoDB documents as well, it's just missing the wiring. I've created a PR, but you can add it manually as well, eg:

```yaml
doctrine_mongodb.odm.entity_value_resolver.expression_language:
    class: Symfony\Component\ExpressionLanguage\ExpressionLanguage

doctrine_mongodb.odm.entity_value_resolve:
    class: Symfony\Bridge\Doctrine\ArgumentResolver\EntityValueResolver
    arguments:
        - '@doctrine_mongodb'
        - '@doctrine_mongodb.odm.entity_value_resolver.expression_language'
    tags:
        - { name: controller.argument_value_resolver, priority: 110 }
```
