### ISSUE TITLE
Doctrine MongoDB Manager named "Doctrine\ODM\MongoDB\DocumentManager" does not exist.

### ISSUE THREAD

**Issue by holisticnetworking** [doctrine/DoctrineMongoDBBundle#871]
|    Q        |   A
|------------ | -----
| Version     | 5.1.0

### Support Question

I'm going to say the documentation leaves something to be desired. If I want to associate two MongoDB documents together, the Bundle offers a DocumentType form type and the documentation informs you of such... and that's it. No instructions on how to use it, no examples. So when I associate two documents, I get the above error message. 

Here is my ReportType.php form class:
```
<?php
/**
 * ReportType - This class is responsible for creating the form for all Reports
 **/
declare(strict_types=1);

namespace App\Form;

use App\Document\Partner;
use App\Document\Report;
use App\Document\State;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\Event\PreSubmitEvent;
use Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType;
use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\Persistence\ObjectManager;

/**
 * ReportType
---------------------
 * This class is responsible for creating the form for the rental entity.
 **/
class ReportType extends AbstractType
{
	/**
	 *  buildForm -  This function is responsible for building the form for the rental entity.
	 *
	 * @param FormBuilderInterface $builder - The form builder interface
	 * @param array                $options - The options for the form
	 */
	public function buildForm(FormBuilderInterface $builder, array $options): void
	{
		$today = new \DateTime();
		$builder
			->add('name', TextType::class)
			->add('date', TextType::class)
			->add('author', TextType::class)
			->add('report_type', TextType::class)
			->add('description', TextType::class)
			->add('partners', DocumentType::class, [
				'class' => Partner::class,
				'choice_label' => 'name',
				'expanded' => true,
				'multiple' => true,
				'document_manager' => DocumentManager::class,
			])
//			->add('states', DocumentType::class, [
//				'class' => State::class,
//				'choice_label' => 'name',
//				'expanded' => true,
//				'multiple' => true,
//			])
			->add('dews_region', TextType::class)
			->add('climate_region', TextType::class);
	}

	/**
	 *  configureOptions - This function is responsible for setting the default options for the form.
	 *
	 * @param OptionsResolver $resolver - The options resolver
	 * */
	public function configureOptions(OptionsResolver $resolver): void
	{
		$resolver->setDefaults(
			[
				'data_class' => Report::class,
				'entityManager' => null,
			]
		);
	}
}
```

How to proceed?

**Comment by malarzm** [comment]
Well, just use it :) The error stems from you explicitly specifying `'document_manager' => DocumentManager::class,` which has Symfony looking for a specific DM. You don't need that option in most scenarios, a document manager instance will be chosen automatically basing on the document you want to associate.

Also, we use GitHub issues for tracking issues with the bundle. Please use [doctrine-odm on StackOverflow](https://stackoverflow.com/questions/tagged/doctrine-odm) for support questions.

**Comment by holisticnetworking** [comment]
Ok, but the dead end I'm reaching is that this is not what the documentation says:
https://www.doctrine-project.org/projects/doctrine-mongodb-bundle/en/latest/form_validation.html

> The only difference is that DocumentType expects the DocumentManager name or instance passed with the document_manager option instead of em.

**Comment by holisticnetworking** [comment]
Furthermore, if I delete that entry I get:

> Symfony\Bridge\Doctrine\Form\Type\DoctrineType::getCachedIdReader(): Argument #1 ($manager) must be of type Doctrine\Persistence\ObjectManager, null given, called in /var/www/clim_rep/vendor/symfony/doctrine-bridge/Form/Type/DoctrineType.php on line 199

**Comment by malarzm** [comment]
> The only difference is that DocumentType expects the DocumentManager name or instance passed with the document_manager option instead of em.

https://symfony.com/doc/current/reference/forms/types/entity.html#em parameter is optional and defaults to a default manager, same in this bundle's case.

A DM's name is whatever you have specified in the configuration's `document_managers` section (https://www.doctrine-project.org/projects/doctrine-mongodb-bundle/en/5.0/config.html#sample-configuration). My guess is that you have incorrectly configured the bundle.

**Comment by holisticnetworking** [comment]
Here is my default config. If the default doesn't work, what hope is there for humanity? LOL:
```yaml
doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: "%env(resolve:MONGODB_URL)%"
    default_database: "%env(resolve:MONGODB_DB)%"
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    dir: "%kernel.project_dir%/src/Document"
                    mapping: true
                    type: attribute
                    prefix: 'App\Document'
                    is_bundle: false
                    alias: App
```
